---
title: "About"
format:
  html: 
    grid:
      sidebar-width: 50px
      margin-width: 50px
      gutter-width: 1.5rem
---

<style>
  body {
  background-image: linear-gradient(rgba(255, 255, 255, 0.55), rgba(255, 255, 255, 0.55)), 
                      url(apples/img/allapples.png);
  background-position: bottom;
  background-size: 100%;
  background-repeat: repeat;
  }

  .table-container {
    display: block;
    width: 100%; 
    margin: 20px auto;
    padding: 10px;
    font-size: 25px;
    background-color: white;
    color: black;
    word-wrap: break-word; 
    border-radius: 10px;
 }
</style>

<body>
    <div class="table-container">
<b>Purpose</b><br>
This website is for sharing the findings of extensive food sensory testing conducted on 30+ apple selections. Our goal is to provide information on the taste, flavor, and texture attributes of these apples, focusing on varieties that hold particular relevance for Ohio growers and consumers. Unlike the more familiar apples commonly found in grocery stores, these selections include unique and lesser-known varieties. We aim to educate and inspire both growers and consumers, showcasing the diverse and flavorful apple options well-suited to growth Ohio.

<b>What is food sensory evaluation?</b><br>
Sensory evaluation uses humans as instruments to analyze the sensory properties of foods, drinks, and other consumer products. Using these techniques, we were able to evaluate the taste, aroma, flavor, and texture of the apples in this project. We were also able to gain insights into what aspects of these apples consumers like.

For more information about the food sensory testing, please select 'Descriptive Analysis' or 'Consumer Testing' in the drop-down menu under 'About.'

<b>Research team</b><br>
Dr. Jessica Cooperstone, Dr. Diane Miller, Dr. Jonathan Fresnedo Ramírez, Dr. Chris Simons, and hard-working graduate students (Lydia Balogh, MSc., and others) at The Ohio State University.

This project was sponsored by the Ohio Department of Agriculture (ODA, award AM22SCBPOH1157) Specialty Block Grant and the United States Department of Agriculture (USDA, award 2023-67013-40267) and supported by the Midwest Apple Foundation (MAF). We thank the many Ohio and midwestern apple growers who have provided apples for our studies.
</div>
</body>
