
---
title: "Discover Ohio's Hidden Apple Gems"
format: html
---
<style>
  body {
  background-image: linear-gradient(rgba(255, 255, 255, 0.55), rgba(255, 255, 255, 0.55)), 
                      url(apples/img/allapples.png);
  background-position: bottom;
  background-size: 100%;
  background-repeat: repeat;
}

  .table-container {
    display: block;
    width: 100%; 
    margin: 20px auto;
    padding: 10px;
    font-size: 25px;
    background-color: white;
    color: black;
    text-align: center;
    word-wrap: break-word; 
    border-radius: 10px;
 }
</style>

<body>
    <div class="table-container">
    
The goal of this website is to share data collected at The Ohio State University on the traits of Ohio apples valuable to local growers.

Whether you're an apple grower seeking to diversify your orchard or a curious eater eager to explore new flavors, this resource highlights Ohio's unique apple offerings.

Select 'About' at the top to learn more, or 'Apples' to choose an apple to learn more about. 

We would love to hear from you! [Click here to provide feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=NlYJ61IQlUiVKx_53x0RIQ3Y-LAlMblCs4MqMuZ7I5hUM1lOMkg2QU5EUU5PQjRSNVFWRlQxVjlBUC4u) or email balogh.67@osu.edu 
</div>
</body>